name: Lint, test and format chatblib

on:
  pull_request:
    paths:
      - "chatlib/**"
  workflow_run:
    workflows: ["Dependabot PR Check"]
    types:
      - completed

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.7"]

    defaults:
      run:
        working-directory: chatlib

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: "chatlib"
          sparse-checkout-cone-mode: false

      - name: ğŸ Set up Python ${{ matrix.python-version }} 
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: ğŸ“œ Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: ğŸš€ Cache the venv based on the .lock 
        uses: actions/cache@v3
        with:
          path: chatlib/.venv
          key: venv-${{ hashFiles('chatlib/poetry.lock') }}

      - name: ğŸ”¨ Install dev dependencies
        run: poetry install --with dev

      - name: ğŸ§‘â€ğŸ”§ Lint with ruff
        run: poetry run ruff check .

      - name: ğŸ§¹ Format with black
        run: poetry run black --check .

      - name: ğŸ§ª Run tests
        run: poetry run pytest
        env:
          WIKIJS_API_TOKEN: ${{ secrets.WIKIJS_API_TOKEN }}
